version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/appdb
      SECRET_KEY: dev-secret-change-me
      CREATE_DEMO_USER: "1"
      DEMO_USERNAME: student
      DEMO_PASSWORD: password123
      DEMO_TOTP_SECRET: JBSWY3DPEHPK3PXP
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  dbdata:
