version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    command: gunicorn -b 0.0.0.0:5000 run:app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flaskdb
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:16
    container_name: flask_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
