version: "3.9"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            FLASK_ENV: development
            FLASK_DEBUG: "1"
        volumes:
            - .:/app
        command: flask --app app run --host=0.0.0.0 --port=5000
