version: "3.9"

services:
    db:
        image: postgres:16
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
            POSTGRES_DB: appdb
        volumes:
            - dbdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
            interval: 5s
            timeout: 3s
            retries: 10
    web:
        build:
            context: ../..
            dockerfile: docker/production/Dockerfile
        ports:
            - "8000:8000"
        environment:
            FLASK_ENV: production
            FLASK_DEBUG: "0"
            DATABASE_URL: postgresql://app:app@db:5432/appdb
        depends_on:
            db:
                condition: service_healthy
        restart: always
        command: gunicorn --bind 0.0.0.0:8000 app:app
    test:
        build:
            context: ../..
            dockerfile: docker/production/Dockerfile
        command: ["python", "/app/run_simple_checks.py"]
        depends_on:
            - web
        environment:
            - APP_BASE_URL=http://web:8000/
            - APP_CHECK_TIMEOUT=20
volumes:
    dbdata:
