name: CI

on:
    pull_request:
        branches: [main] # testa PR verso main (prima del merge)
        paths: ["**/*.py", "tests/**", "requirements.txt"]
    push:
        branches: [main] # ritesta dopo il merge su main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
                  cache: "pip"
            - run: pip install -r requirements.txt
            - run: pytest -q
